trigger:
- master

steps:
- task: Docker@2
  displayName: Build test container
  inputs:
    command: build
    Dockerfile: ./client/Dockerfile.dev
    buildContext: ./client
    arguments: -t julio/react-test

- script: |
    docker run -e CI=true julio/react-test npm test
  displayName: Run React Container


- task: Docker@2
  displayName: Login to Docker hub
  inputs:
    command: Login
    containerRegistry: jisolarteDockerHub

- task: Docker@2
  displayName: Build and Push client image to Docker hub
  inputs:
    command: buildAndPush
    repository: julio/react-client
    buildContext: ./client
    tags: latest

- task: Docker@2
  displayName: Build and Push server image to Docker hub
  inputs:
    command: buildAndPush
    repository: julio/react-server
    buildContext: ./server
    tags: latest

- task: Docker@2
  displayName: Build and Push nginx image to Docker hub
  inputs:
    command: buildAndPush
    repository: julio/react-nginx
    buildContext: ./nginx
    tags: latest

- task: Docker@2
  displayName: Build and Push worker image to Docker hub
  inputs:
    command: buildAndPush
    repository: julio/react-worker
    buildContext: ./worker
    tags: latest


