trigger:
- master

steps:
- task: Docker@2
  displayName: Build test container
  inputs:
    command: build
    Dockerfile: ./client/Dockerfile.dev
    buildContext: ./client
    arguments: -t julio/react-test

- script: |
    docker run -e CI=true julio/react-test npm test
  displayName: Run React Container

- script: |
    docker build -t julio/react-client ./client
    docker build -t julio/react-server ./server
    docker build -t julio/react-nginx ./nginx
    docker build -t julio/react-worker ./worker
  displayName: Build production images

- task: Docker@2
  displayName: Login to Docker hub
  inputs:
    command: Login
    containerRegistry: jisolarteDockerHub

- task: Docker@2
  displayName: Push client image to Docker hub
  inputs:
    command: push
    repository: docker-app
    tags: |
      julio/react-client
      julio/react-server
      julio/react-nginx
      julio/react-worker
